In [2]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
li1 = [
    [1, 2, 3],
    [4, 5, 6],
    [1, 2, 3],
    [4, 5, 6],
    [1, 2, 3],
    [4, 5, 6],
    [1, 2, 3],
    [4, 5, 6],
    [1, 2, 3],
    [4, 5, 6],
    [1, 2, 3],
    [4, 5, 6]
]
print(li1)
print(type(li1))

[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]
<class 'list'>


In [8]:
arr3 = np.array([
    [[1, 2],
     [3, 4]],
     [[5, 6],
      [7, 8]]
])

print(arr3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [10]:
zeros = np.zeros(5)
print(zeros)

[0. 0. 0. 0. 0.]


In [13]:
ones = np.ones((3, 3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [15]:
range_arr = np.arange(1, 10, 2)     # arange 함수와 비슷함
print(range_arr)

[1 3 5 7 9]


In [20]:
# 데이터 타입

정수 = np.array([1, 2, 3, 4, 5])
print(정수.dtype)
실수 = np.array([1.5, 2.5, 3.5])
print(실수.dtype)


int64
float64


In [ ]:
# 배열 속성

arr1 = np.array([1, 2, 3, 4])
print(arr1.shape)       # (4, ) -> 1차원, 4행

arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(arr2.shape)       # (2, 3) -> 2차원, 2행 3열

arr3 = np.array([
    [[1, 2],
     [3, 4]],
     [[5, 6],
      [7, 8]]
])
print(arr3.shape)       # (2, 2 ,2) -> 3차원 / 텐서

(4,)
(2, 3)
(2, 2, 2)


In [26]:
# ndim -> 차원 출력
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
3


In [32]:
# size - 배열의 총 요소 수를 알려준다.

arr1 = np.array([1, 2, 3, 4])
print(arr1.size)

arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(arr2.size)

arr3 = np.array([
    [[1, 2],
     [3, 4]],
     [[5, 6],
      [7, 8]]
])
print(arr3.size)

4
6
8
