In [1]:
# reshape
import numpy as np

In [14]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr.shape)

(6,)


In [13]:
reshaped = arr.reshape((2, 3))
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [20]:
print(reshaped.shape)

(2, 3)


In [6]:
# astype
## 데이터타입을 변경한다

arr = np.array([1, 2, 3, 4, 5, 6])
float_arr = arr.astype(float)
print(float_arr)

[1. 2. 3. 4. 5. 6.]


In [18]:
# ravel
## 다차원 배열을 1차원 배열로 변경

arr = np.array([1, 2, 3, 4, 5, 6])
reshpaed = arr.reshape((2, 3))
print(reshaped)

raveled = reshaped.ravel()
print(raveled)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [19]:
# flaten
## 다차원 배열을 1차원 배열로 변경

arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(arr)
flattened = arr.flatten()
print(flattened)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [22]:
# transpose
## 배열의 축을 바꾸는 함수

arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

transposed = arr.transpose()
print(transposed)

[[1 4]
 [2 5]
 [3 6]]


In [27]:
# 수학 연산

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 / arr2)
print(arr1 * arr2)

[5 7 9]
[-3 -3 -3]
[0.25 0.4  0.5 ]
[ 4 10 18]


In [34]:
# 배열 간 비교 연산

arr1 = np.array([5, 3, 3])
arr2 = np.array([1, 2, 6])

print(arr1 != arr2)

[ True  True  True]


In [39]:
# 배열 간 논리 연산

arr1 = np.array([True, False, True])
arr2 = np.array([False, True, True])

print(arr1 & arr2)
print(arr1 | arr2)

[False False  True]
[ True  True  True]


In [42]:
# 배열 간 집계 연산
arr = np.array([1, 2, 3, 4, 5])
print(arr.sum())
print(arr.mean())
print(arr.min())
print(arr.max())

15
3.0
1
5


In [44]:
arr = np.array([1, 2, 3, 4, 5])
scalar = 2
print(arr * scalar)

[ 2  4  6  8 10]
