In [2]:
# 인덱싱과 슬라이싱

import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[2])

3


In [7]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(arr)
print(arr[1][2])
print(arr[1, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6
6


In [10]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[1:4])

[2 3 4]


In [12]:
cond = arr > 2
# arr[arr > 2]
arr[cond]

array([3, 4, 5])

In [14]:
cond = (arr > 2) & (arr < 5)
print(arr[cond])

[3 4]


In [15]:
# 통계함수
## 평균, 분산, 표준편차, 중앙값, 최빈값

arr = np.array([1, 2, 3, 4, 5])
print("합계", arr.sum())
print("평균", arr.mean())
print("분산", arr.var())
print("표준편차", arr.std())

합계 15
평균 3.0
분산 2.0
표준편차 1.4142135623730951
